Fix "'::strlen' has not been declared" in assimp
Trying to compile it on MSYS2, you will get the error:

    error: '::strlen' has not been declared

Including the additional header **cstring** in **types.h** file fixes this problem. In the long run, it might be best to upgrade the assimp library to version 3.1.1 (released June 2014).